In [13]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from BuildPhIPSeqLibrary.config import AMINO_ACIDS
%matplotlib inline

# Subfigure A

In [12]:
hamming_distance = 1
df = pd.DataFrame({'length_of_barcode': np.arange(3, 100, 3)})
df['num_of_oligos_random'] = 4**length_of_barcode

In [9]:
num_of_oligos_random

array([                 64,                4096,              262144,
                  16777216,          1073741824,         68719476736,
             4398046511104,     281474976710656,   18014398509481984,
       1152921504606846976,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0,
                         0,                   0,                   0])

In [14]:
AMINO_INFO

   amino_acid codon  relative_frequency  corrected_relative_frequency
0           F   TTT                0.57                      0.570000
1           F   TTC                0.43                      0.430000
2           L   TTA                0.15                      0.150000
3           L   TTG                0.12                      0.120000
4           L   CTT                0.12                      0.120000
..        ...   ...                 ...                           ...
59          R   AGG                0.03                      0.030303
60          G   GGT                0.29                      0.290000
61          G   GGC                0.46                      0.460000
62          G   GGA                0.13                      0.130000
63          G   GGG                0.12                      0.120000

[64 rows x 4 columns]

In [37]:
from_web_table = """UUU F 0.57 19.7 (   101)
UCU S 0.11  5.7 (    29)
UAU Y 0.53 16.8 (    86)
UGU C 0.42  5.9 (    30)
UUC F 0.43 15.0 (    77)
UCC S 0.11  5.5 (    28)
UAC Y 0.47 14.6 (    75)
UGC C 0.58  8.0 (    41)
UUA L 0.15 15.2 (    78)
UCA S 0.15  7.8 (    40)
UAA * 0.64  1.8 (     9)
UGA * 0.36  1.0 (     5)
UUG L 0.12 11.9 (    61)
UCG S 0.16  8.0 (    41)
UAG * 0.00  0.0 (     0)
UGG W 1.00 10.7 (    55)
CUU L 0.12 11.9 (    61)
CCU P 0.17  8.4 (    43)
CAU H 0.55 15.8 (    81)
CGU R 0.36 21.1 (   108)
CUC L 0.10 10.5 (    54)
CCC P 0.13  6.4 (    33)
CAC H 0.45 13.1 (    67)
CGC R 0.44 26.0 (   133)
CUA L 0.05  5.3 (    27)
CCA P 0.14  6.6 (    34)
CAA Q 0.30 12.1 (    62)
CGA R 0.07  4.3 (    22)
CUG L 0.46 46.9 (   240)
CCG P 0.55 26.7 (   137)
CAG Q 0.70 27.7 (   142)
CGG R 0.07  4.1 (    21)
AUU I 0.58 30.5 (   156)
ACU T 0.16  8.0 (    41)
AAU N 0.47 21.9 (   112)
AGU S 0.14  7.2 (    37)
AUC I 0.35 18.2 (    93)
ACC T 0.47 22.8 (   117)
AAC N 0.53 24.4 (   125)
AGC S 0.33 16.6 (    85)
AUA I 0.07  3.7 (    19)
ACA T 0.13  6.4 (    33)
AAA K 0.73 33.2 (   170)
AGA R 0.02  1.4 (     7)
AUG M 1.00 24.8 (   127)
ACG T 0.24 11.5 (    59)
AAG K 0.27 12.1 (    62)
AGG R 0.03  1.6 (     8)
GUU V 0.25 16.8 (    86)
GCU A 0.11 10.7 (    55)
GAU D 0.65 37.9 (   194)
GGU G 0.29 21.3 (   109)
GUC V 0.18 11.7 (    60)
GCC A 0.31 31.6 (   162)
GAC D 0.35 20.5 (   105)
GGC G 0.46 33.4 (   171)
GUA V 0.17 11.5 (    59)
GCA A 0.21 21.1 (   108)
GAA E 0.70 43.7 (   224)
GGA G 0.13  9.2 (    47)
GUG V 0.40 26.4 (   135)
GCG A 0.38 38.5 (   197)
GAG E 0.30 18.4 (    94)
GGG G 0.12  8.6 (    44)"""
from_web_table = pd.DataFrame({'whole_str': from_web_table.split('\n')})
from_web_table['codon'] = from_web_table.whole_str.str.split().str[0]
from_web_table['amino_acid'] = from_web_table.whole_str.str.split().str[1]
from_web_table['fraction'] = from_web_table.whole_str.str.split().str[2].astype(float)
from_web_table['frequency_per_thousand'] = from_web_table.whole_str.str.split().str[3].astype(float)

In [38]:
from_web_table.head()

                  whole_str codon amino_acid  fraction  frequency_per_thousand
0  UUU F 0.57 19.7 (   101)   UUU          F      0.57                    19.7
1  UCU S 0.11  5.7 (    29)   UCU          S      0.11                     5.7
2  UAU Y 0.53 16.8 (    86)   UAU          Y      0.53                    16.8
3  UGU C 0.42  5.9 (    30)   UGU          C      0.42                     5.9
4  UUC F 0.43 15.0 (    77)   UUC          F      0.43                    15.0

In [51]:
frequency_per_aa = from_web_table.groupby('amino_acid').frequency_per_thousand.sum().drop(index='*').to_frame()
frequency_per_aa['frequency_per_thousand'] /= frequency_per_aa['frequency_per_thousand'].sum()

num_options_per_aa = from_web_table.groupby('amino_acid').codon.count()

In [64]:
res = {}
for barcode_aa_length in range(1, 10):
    rounds = []
    for round_i in range(1000):
        if round_i%10==0:
            print(f"In round {round_i}")
        res = {}
        for i in range(1000000):
            sequence = np.random.choice(frequency_per_aa.index, size=barcode_aa_length, 
                                        p=frequency_per_aa['frequency_per_thousand'])
            num_options = res.get(''.join(sequence), np.prod(list(map(num_options_per_aa.get, sequence))))
            if num_options == 0:
                break
            res[''.join(sequence)] = num_options - 1
        rounds.append(i)
    pd.Series(rounds).to_csv(f"round_for_{barcode_aa_length}.csv")
    res[barcode_aa_length] = rounds

In round 0
In round 10
In round 20
In round 30
In round 40
In round 50
In round 60
In round 70
In round 80
In round 90
In round 100
In round 110
In round 120
In round 130
In round 140
In round 150
In round 160
In round 170
In round 180

KeyboardInterrupt: